### ISSUE TITLE
Encountered compilation errors while building app manager for Zephyr

### ISSUE THREAD

**Issue by lucasAbadFr** [bytecodealliance/wamr-app-framework#6]
Hello, I'm attempting to adapt the `simple` sample to function as a Zephyr app directly, without utilizing `wasm-micro-runtime` as a module. However, during this process, **I encountered 2 issues:**

###  `wasm_runtime_lookup_function`
---

Since this [commit](https://github.com/bytecodealliance/wasm-micro-runtime/commit/c3e33a96eaef15b086d2d0115d916f276476b749) the `wasm_runtime_lookup_function` definition has changed:
```diff
wasm_runtime_lookup_function(WASMModuleInstanceCommon *const module_inst,
-                             const char *name, const char *signature)
+                             const char *name)
```

So it need to be fixed in `app-mgr/app-manager/module_wasm_app.c`
```diff
diff --git a/app-mgr/app-manager/module_wasm_app.c b/app-mgr/app-manager/module_wasm_app.c
index 6fd929b..979a3f3 100644
--- a/app-mgr/app-manager/module_wasm_app.c
+++ b/app-mgr/app-manager/module_wasm_app.c
@@ -193,9 +193,9 @@ app_manager_lookup_function(const wasm_module_inst_t module_inst,
 {
     wasm_function_inst_t func;

-    func = wasm_runtime_lookup_function(module_inst, name, signature);
+    func = wasm_runtime_lookup_function(module_inst, name);
     if (!func && name[0] == '_')
-        func = wasm_runtime_lookup_function(module_inst, name + 1, signature);
+        func = wasm_runtime_lookup_function(module_inst, name + 1);
     return func;
 }
```
>📄: **Notes:** May be removing the `const char *signature` argument need to be done for `app_manager_lookup_function`, but I didn't go that far.

### The `host-tool` build Policy
---
In the `CMakeList.txt`, it's hardcoded in a way that we need to clone the repo with submodules. I also saw that a PR is open to address this issue but it's a month old.
```cmake
22 set (IWASM_DIR  ${REPO_ROOT_DIR}/deps/wasm-micro-runtime/core/iwasm)
24 set (SHARED_DIR ${REPO_ROOT_DIR}/deps/wasm-micro-runtime/core/shared)
```
But In my case I have a fork of `wasm-micro-runtime` and I want to use this environment. So this cause this kind of errors when I build:
```bash
CMake Error at CMakeLists.txt:49 (include):
  include could not find requested file:

    /home/user/wamr-app-framework/test-tools/host-tool/../../deps/wasm-micro-runtime/core/shared/platform/linux/shared_platform.cmake


CMake Error at CMakeLists.txt:50 (include):
  include could not find requested file:

    /home/user/wamr-app-framework/test-tools/host-tool/../../deps/wasm-micro-runtime/core/shared/utils/shared_utils.cmake


CMake Error at CMakeLists.txt:51 (include):
  include could not find requested file:

    /home/user/wamr-app-framework/test-tools/host-tool/../../deps/wasm-micro-runtime/core/shared/mem-alloc/mem_alloc.cmake


CMake Error at CMakeLists.txt:53 (include):
  include could not find requested file:

    /home/user/wamr-app-framework/test-tools/host-tool/../../deps/wasm-micro-runtime/core/shared/coap/lib_coap.cmake
```
>📄: **Notes:** I commented my implementation, that why the lines correspond to nothing, but the errors come from:
>```cmake
>31 include (${SHARED_DIR}/platform/${WAMR_BUILD_PLATFORM}/shared_platform.cmake)
>32 include (${SHARED_DIR}/utils/shared_utils.cmake)
>33 include (${SHARED_DIR}/mem-alloc/mem_alloc.cmake)
>35 include (${SHARED_DIR}/coap/lib_coap.cmake)
>```

So I propose to change the build policy to something like that:
```cmake
# Treatment for SHARED_DIR and IWASM_DIR 
# if:
#     1. WAMR_ROOT_DIR or WAMR_DIR are set in the env 
#     2. The submodules exist. 
# else: 
#     Throw an error message
if(DEFINED ENV{WAMR_ROOT_DIR})
    set(CORE_DIR $ENV{WAMR_ROOT_DIR}/core)
elseif(DEFINED ENV{WAMR_DIR})
    set(CORE_DIR $ENV{WAMR_DIR/core})
elseif(IS_DIRECTORY ${REPO_ROOT_DIR}/deps/wasm-micro-runtime/core/)
    set(CORE_DIR ${REPO_ROOT_DIR}/deps/wasm-micro-runtime/core/)
else()
    message(FATAL_ERROR "'WAMR_ROOT_DIR' or 'WAMR_DIR' environment variables are not set and\
                         the directory '${REPO_ROOT_DIR}/deps/wasm-micro-runtime/core/' does not exist.\
                         Please set one of these environment variables or clone the git repository with submodules.")
endif()

set(IWASM_DIR  ${CORE_DIR}/iwasm)
set(SHARED_DIR ${CORE_DIR}/shared)
```

>📄: **Notes:** The `WAMR_ROOT_DIR` or `WAMR_DIR` could be set in an other `CMakeList.txt` file, exported in a `.sh`, or passed as command line parameters. 

I'm also quite interested in the setup used for the `app-manager` demo on Zephyr, because I'm able to make it compile but it doesn't work as expected, and the readme doesn't really detail this aspect. Should I open an issue on `wasm-micro-runtime` or pass by another mean of communication ?

**Comment by TianlongLiang** [comment]
Thanks for reporting this issue, the compilation error and source code should be fixed with those two PRs: https://github.com/bytecodealliance/wamr-app-framework/pull/6 and https://github.com/bytecodealliance/wamr-app-framework/pull/7

As for your question:

> I'm also quite interested in the setup used for the `app-manager` demo on Zephyr, because I'm able to make it compile but it doesn't work as expected, and the readme doesn't really detail this aspect. Should I open an issue on `wasm-micro-runtime` or pass by another mean of communication ?

I think we can discuss it here since it's `app-manager` related issue, could you please share more details about the unexcepted behavior?

**Comment by wenyongh** [comment]
@lucasAbadFr The PR #7 was merged to fix the compilation errors, could you try again?

**Comment by lucasAbadFr** [comment]
First of all thanks for your quick replies.

#### Compilation
@wenyongh  I tried to re-build the example and it worked without any compilation errors. To do that I had to clone the `wasm-micro-runtime` with the `download.sh` script. I have a suggestion to improve it see [suggestion part](#Suggestion)  

#### Zephyr setup 
@TianlongLiang I was interested on how you managed the UART part of your sample, and particularly how you plugged the UART.

The unexpected behavior was actually a misunderstanding on my part I was able to make the `app-manager` boot but it didn't respond to any `host-tool` request. As I didn't have any UART plugged I was expecting the `host-tool` or the `app-manager` to return an error message but nothing happened.

I did A little work around on my end by 'mapping' the UART to the user usb-c available on my board. Then I was able to see the `app-manager` booting and responding to the `host-tool` request. 

I encontered some timeouts, but I didn't have time to investigate was it also the case for you ? I observed that after a timeout If I send the same request then it work.

#### Suggestion
When re-trying to build the example I used the `download.sh` script to clone the `wasm-micro-runtime` repository. I think it would be a good idea to be more flexible on the `download.sh` script. Because I had to comment the part about `lv_drivers` and `lvgl` to get just `wasm-micro-runtime`. I suggest to use env variables to allow the user to choose which dependencies he wants to clone.

e.g: 
1. `download.sh`:
    ```bash
    if [ "${WAMR}" == "1" ]; then
        if [ ! -d "wasm-micro-runtime" ]; then
            echo "git pull wasm-micro-runtime..."
            git clone https://github.com/bytecodealliance/wasm-micro-runtime.git
            [ $? -eq 0 ] || exit $?
        fi
    fi
    ```
2. Usage:
    ```bash
    WAMR=1 ./download.sh
    ```

3. `Readme.md`

    Adding a `Readme.md` file to the `deps/` folder to explain how to use the `download.sh` script. Listing the dependencies and explaining why they are needed. Then explaining how to use the `download.sh` script to clone the dependencies.


Following your feedbacks, I will close the issue as the compilation errors where fixed.

**Comment by TianlongLiang** [comment]
I only tested it on my Ubuntu machine, I don't have a physical board to test it on.  I see there is a macro in the sample `simple`: https://github.com/TianlongLiang/wamr-app-framework/blob/ded92a3f7d9cef3115d2493d799c0d265c326b70/samples/simple/CMakeLists.txt#L36 Maybe you can add it in your application to try if it works

Per your suggestion, I created this pr https://github.com/bytecodealliance/wamr-app-framework/pull/8 feel free to leave some comments

**Comment by lucasAbadFr** [comment]
I think the PR name is quite explicit. I'm closing this issue.
